Repository actor-framework/incubator, pull requests merged in 2019-09, with the labels that each got.

#19 Add udp_datagram_socket
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/detail/convert_ip_endpoint.hpp
  libcaf_net/caf/net/udp_datagram_socket.hpp
  libcaf_net/src/convert_ip_endpoint.cpp
  libcaf_net/src/udp_datagram_socket.cpp
  libcaf_net/test/convert_ip_endpoint.cpp
  libcaf_net/test/udp_datagram_socket.cpp
Labels: new feature

#20 Add transport_worker_dispatcher
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/transport_worker_dispatcher.hpp
  libcaf_net/test/transport_worker_dispatcher.cpp
Labels: new feature

#23 Resolve empty strings to "any" address
  libcaf_net/src/ip.cpp
  libcaf_net/test/ip.cpp
Labels: bugfix

#25 Simplify socket design
  libcaf_net/caf/net/abstract_socket.hpp
  libcaf_net/caf/net/datagram_socket.hpp
  libcaf_net/caf/net/network_socket.hpp
  libcaf_net/caf/net/pipe_socket.hpp
  libcaf_net/caf/net/socket.hpp
  libcaf_net/caf/net/socket_id.hpp
  libcaf_net/caf/net/stream_socket.hpp
  libcaf_net/caf/net/tcp_accept_socket.hpp
  libcaf_net/caf/net/tcp_stream_socket.hpp
  libcaf_net/caf/net/udp_datagram_socket.hpp
  libcaf_net/src/stream_socket.cpp
  libcaf_net/src/tcp_accept_socket.cpp
  libcaf_net/src/tcp_stream_socket.cpp
  libcaf_net/test/socket_guard.cpp
  libcaf_net/test/udp_datagram_socket.cpp
Labels: refactoring

#26 Add write overload for multiple buffers
  libcaf_net/caf/net/stream_socket.hpp
  libcaf_net/src/stream_socket.cpp
  libcaf_net/test/stream_socket.cpp
Labels: new feature

#22 Add function to resolve local addresses and interface names
  libcaf_net/caf/net/ip.hpp
  libcaf_net/src/ip.cpp
  libcaf_net/test/ip.cpp
Labels: new feature
